name: newsapp
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  dio: ^5.4.3+1
  url_launcher: ^6.2.6
  json_annotation: ^4.9.0
  build_runner: ^2.3.3
  json_serializable: ^6.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  
  
  
  
  
  flutter_lints: ^3.0.0





flutter:

  
  
  
  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
